### ISSUE TITLE
Error in Reto3b/src/reto4/FileReader.java

### ISSUE THREAD

**Issue by tomatniy** [simongomez95/Computer-Graphics#1]
How to solve:
Move "int[] arista = new int[2];" in for loop so you will get:
aristaStr = br.readLine().split(" ");
int[] arista = new int[2];
arista[0] = Integer.parseInt(aristaStr[0]);
arista [1] = Integer.parseInt(aristaStr[1]);
listaAristas.add(arista);

**Comment by simongomez95** [comment]
Thank you a lot man!
